<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.app_command_resetdatabasecommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/ResetDatabaseCommand.php';

return $this->services['console.command.app_command_resetdatabasecommand'] = new \App\Command\ResetDatabaseCommand();
