<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AddController:add' => function () {
    return ($this->privates['service_locator.4Giebjo'] ?? $this->load(__DIR__.'/getServiceLocator_4GiebjoService.php'));
}, 'App\\Controller\\DefaultController:index' => function () {
    return ($this->privates['service_locator.OXGnpIQ'] ?? $this->load(__DIR__.'/getServiceLocator_OXGnpIQService.php'));
}, 'App\\Controller\\DefaultController:indexa' => function () {
    return ($this->privates['service_locator.OXGnpIQ'] ?? $this->load(__DIR__.'/getServiceLocator_OXGnpIQService.php'));
}, 'App\\Controller\\ProfileController:profile' => function () {
    return ($this->privates['service_locator.RDnvng_'] ?? $this->load(__DIR__.'/getServiceLocator_RDnvngService.php'));
}, 'App\\Controller\\SecurityController:loginAction' => function () {
    return ($this->privates['service_locator.zp3v.Fu'] ?? $this->load(__DIR__.'/getServiceLocator_Zp3v_FuService.php'));
}, 'App\\Controller\\AddController::add' => function () {
    return ($this->privates['service_locator.4Giebjo'] ?? $this->load(__DIR__.'/getServiceLocator_4GiebjoService.php'));
}, 'App\\Controller\\DefaultController::index' => function () {
    return ($this->privates['service_locator.OXGnpIQ'] ?? $this->load(__DIR__.'/getServiceLocator_OXGnpIQService.php'));
}, 'App\\Controller\\DefaultController::indexa' => function () {
    return ($this->privates['service_locator.OXGnpIQ'] ?? $this->load(__DIR__.'/getServiceLocator_OXGnpIQService.php'));
}, 'App\\Controller\\ProfileController::profile' => function () {
    return ($this->privates['service_locator.RDnvng_'] ?? $this->load(__DIR__.'/getServiceLocator_RDnvngService.php'));
}, 'App\\Controller\\SecurityController::loginAction' => function () {
    return ($this->privates['service_locator.zp3v.Fu'] ?? $this->load(__DIR__.'/getServiceLocator_Zp3v_FuService.php'));
})));
