<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXC7VXQ6\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXC7VXQ6/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXC7VXQ6.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXC7VXQ6\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXC7VXQ6\srcDevDebugProjectContainer();
